name: Deploy

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Branch name
        run: echo running on branch ${GITHUB_REF##*/}
      - name: Deploying to server
        run: |
          bash ./.github/deploy.sh -b ${GITHUB_REF##*/} -m "${{ github.event.head_commit.message }}" -p "${{ secrets.SSH_PASSWORD }}"
